name: CMDM

## modeling space
input_feats: -1
data_repr: 'pos'

## time embedding
time_emb_dim: 512

## conditions
contact_model:
  contact_type: 'contact_cont_joints'
  contact_joints: [0, 10, 11, 12, 20, 21]
  planes: [32, 64, 128, 256]
  num_points: ${task.dataset.num_points}
  blocks: [2, 2, 2, 2]

text_model:
  version: 'ViT-B/32'
  max_length: 32

## model architecture
arch: 'trans_enc'
latent_dim: 512
mask_motion: true
num_layers: [1, 1, 1, 1, 1]
num_heads: 8
dropout: 0.1
dim_feedforward: 1024