name: CMDM

## modeling space
input_feats: -1
data_repr: 'pos'

## time embedding
time_emb_dim: 512

## conditions
## 1. contact
contact_model:
  contact_type: 'contact_cont_joints' # ['contact_one_joints', 'contact_all_joints', 'contact_cont_joints', 'contact_pelvis']
  contact_joints: [0, 10, 11, 12, 20, 21]

  planes: [32, 64, 128, 256]
  num_points: ${task.dataset.num_points}
  blocks: [2, 2, 2, 2]

## 2. text
text_model:
  version: 'ViT-B/32'
  max_length: 32

## model architecture
# arch: 'trans_enc'
# latent_dim: 512
# mask_motion: true
# num_layers: [1,1,1,1,1]
# num_heads: 8
# dropout: 0.1
# dim_feedforward: 1024


arch: 'trans_DCA' 

# 1. 保留共享参数：这些对于新架构中的自注意力模块仍然是必需的
latent_dim: 512
mask_motion: true
num_layers: [1, 1, 1, 1, 1]  # 自注意力模块的总深度将是 sum(num_layers) = 5
num_heads: 8
dropout: 0.1
dim_feedforward: 1024

# 2. 新增并修正 dca 配置项：为 CrossDCA 模块提供专属的超参数
dca:
  patch: 28          # 特征图被下采样到的中间尺寸
  strides: [8, 4, 2, 1]  # 用于上采样恢复分辨率，其长度(4)决定了下方列表的长度
  n_blocks: 1        # 堆叠的注意力块数量
  
  # --- 关键修正 ---
  # 因为有4个特征尺度(由strides的长度决定)，所以head参数也必须是长度为4的列表
  channel_head: [1, 1, 1, 1]
  spatial_head: [4, 4, 4, 4]